# Multilayer Perceptron

Historicamente, Perceptron foi o nome dado a um modelo de rede neural com uma única camada linear. Se o modelo tem múltiplas camadas, chamamos de Perceptron Multicamada (MLP - Multilayer Perceprtron). Cada nó na primeira camada recebe uma entrada e dispara de acordo com os limites de decisão locais predefinidos (thresholds). Em seguida, a saída da primeira camada é passada para a segunda camada, cujos resultados são passados para a camada de saída final consistindo de um único neurônio. 

A rede pode ser densa, o que significa que cada neurônio em uma camada está conectado a todos os neurônios localizados na camada anterior e a todos os neurônios na camada seguinte.

### Treinando Redes Neurais com Keras

Vamos considerar um único neurônio. Quais são as melhores escolhas para o peso w e o bias b? Idealmente, gostaríamos de fornecer um conjunto de exemplos de treinamento e deixar o computador ajustar o peso e o bias de tal forma que os erros produzidos na saída sejam minimizados. A fim de tornar isso um pouco mais concreto, vamos supor que temos um conjunto de imagens de gatos e outro conjunto separado de imagens que não contenham gatos. Por uma questão de simplicidade, suponha que cada neurônio olhe para um único valor de pixel de entrada. Enquanto o computador processa essas imagens, gostaríamos que nosso neurônio ajustasse seus pesos e bias para que tenhamos menos e menos imagens erroneamente reconhecidas como não-gatos. Essa abordagem parece muito intuitiva, mas exige que uma pequena alteração nos pesos (e/ou bias) cause apenas uma pequena mudança nas saídas.

Se tivermos um grande salto de saída, não podemos aprender progressivamente. Afinal, as crianças aprendem pouco a pouco. Infelizmente, o perceptron não mostra esse comportamento "pouco a pouco". Um perceptron é 0 ou 1 e isso é um grande salto e não vai ajudá-lo a aprender. Precisamos de algo diferente, mais suave. Precisamos de uma função que mude progressivamente de 0 para 1 sem descontinuidade. Matematicamente, isso significa que precisamos de uma função contínua que nos permita calcular a derivada.

Cada neurônio pode ser inicializado com pesos específicos. Keras oferece algumas opções, a mais comum são:

Random_uniform: Os pesos são inicializados com valores uniformemente pequenos e aleatórios em (-0,05, 0,05). 

Random_normal: Os pesos são inicializados de acordo com uma distribuição Gaussiana, com média zero e pequeno desvio padrão de 0,05. 

Zero: Todos os pesos são inicializados para zero.

In [1]:
# !pip install keras
# !pip install tensorflow
# !pip install scikit-learn
# !pip install numpy

In [2]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
import numpy 

Using TensorFlow backend.
/Users/vladimiralencar/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)


In [3]:
# Random seed
seed = 7
numpy.random.seed(seed)

https://archive.ics.uci.edu/ml/datasets/pima+indians+diabetes

In [5]:
# Dataset Diabetes
# 1. Number of times pregnant
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
# 3. Diastolic blood pressure (mm Hg)
# 4. Triceps skin fold thickness (mm)
# 5. 2-Hour serum insulin (mu U/ml)
# 6. Body mass index (weight in kg/(height in m)^2)
# 7. Diabetes pedigree function
# 8. Age (years)
# 9. Class variable (0 or 1)

In [6]:
# Carregando o dataset
file = "data.csv"
dataset = numpy.loadtxt("data.csv", delimiter=",")
dataset[:2]

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ,   0.   ]])

In [7]:
# Imprime o dataset
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [8]:
# Split em variáveis de input (X) e output (Y) 
X = dataset[:,0:8]
Y = dataset[:,8]

In [9]:
# split into 67% for train and 33% for test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=seed)

## Colocar os dados em Escala (Padronização)

In [10]:
mu, sigma = X_train.mean(axis=0), X_train.std(axis=0)
X_train = (X_train - mu) / sigma

mu, sigma = X_test.mean(axis=0), X_test.std(axis=0)
X_test = (X_test - mu) / sigma

In [14]:
numpy.set_printoptions(precision=4, suppress=True)
X_test[:3]

array([[-0.86  , -1.1281, -0.4467, -0.5708, -0.326 , -0.5625,  0.262 ,
        -0.8511],
       [ 0.8356,  1.8639,  0.7   , -0.0025,  0.8771,  0.5194,  0.2801,
         1.3481],
       [ 2.5311,  0.9104,  1.0127,  0.7553, -0.4391, -0.6122,  0.7177,
         0.6965]])

https://keras.io/initializers/

In [15]:
# Cria o modelo
# kernel_initializer - inicialização dos pesos

model = Sequential()
model.add(Dense(12, input_dim = 8, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(8, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 12)                108       
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


![Neural network 1 hidden layer](01-arquitetura-rede-neural.png "Rede Neural com 1 Camada Oculta")

### Função Sigmóide

A função sigmóide é uma função matemática de amplo uso em campos como a economia e a computação. O nome "sigmóide" vem da forma em S do seu gráfico. Um neurônio pode usar o sigmóide para calcular a função não-linear. Um neurônio com ativação sigmóide tem um comportamento semelhante ao perceptron, mas as mudanças são graduais e os valores de saída, como 0.3537 ou 0.147191, são perfeitamente legítimos. A função de ativação sigmóide é comumente utilizada por redes neurais com propagação positiva (Feedforward) que precisam ter como saída apenas números positivos, em redes neurais multicamadas e em outras redes com sinais contínuos.

### Função ReLu

O sigmóide não é o único tipo de função de ativação suave usada para redes neurais. Recentemente, uma função muito simples chamada unidade linear rectificada (ReLU) tornou-se muito popular porque gera resultados experimentais muito bons. Uma ReLU é simplesmente definida como uma função não-linear e a função é zero para valores negativos e cresce linearmente para valores positivos.
Sigmoid e ReLU são geralmente chamados funções de ativação das redes neurais. Essas mudanças graduais, típicas das funções Sigmóide e ReLU, são os blocos básicos para o desenvolvimento de um algoritmo de aprendizado que se adapta pouco a pouco, reduzindo progressivamente os erros cometidos pelas redes.

In [17]:
# Compilação do modelo
# Precisamos selecionar o otimizador que é o algoritmo específico usado para atualizar pesos enquanto 
# treinamos nosso modelo.
# Precisamos selecionar também a função objetivo que é usada pelo otimizador para navegar no espaço de pesos 
# (frequentemente, as funções objetivo são chamadas de função de perda (loss) e o processo de otimização é definido 
# como um processo de minimização de perdas).
# Outras funções aqui: https://keras.io/losses/
# A função objetivo "categorical_crossentropy" é a função objetivo adequada para predições de rótulos multiclass e 
# binary_crossentropy para classificação binária. 
# A métrica é usada para medir a performance do modelo. Outras métricas: https://keras.io/metrics/
# As métricas são semelhantes às funções objetivo, com a única diferença de que elas não são usadas para 
# treinar um modelo, mas apenas para avaliar um modelo. 
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy']) # loss - treina o modelo
                                                                                        # metrics - avalia o modelo

In [19]:
len(X_train)

514

In [18]:
# Treinamento do modelo
# Epochs: Este é o número de vezes que o modelo é exposto ao conjunto de treinamento. Em cada iteração, 
# o otimizador tenta ajustar os pesos para que a função objetivo seja minimizada. 
# Batch_size: Esse é o número de instâncias de treinamento observadas antes que o otimizador execute uma 
# atualização de peso.
model.fit(X_train, y_train, epochs = 200, batch_size = 10)

Epoch 1/200
514/514 [==============================] - 2s 3ms/step - loss: 0.6891 - acc: 0.6576A: 4s - loss: 0.6922 - acc: 0.
Epoch 2/200
514/514 [==============================] - 0s 824us/step - loss: 0.6631 - acc: 0.6576
Epoch 3/200
514/514 [==============================] - 0s 749us/step - loss: 0.5913 - acc: 0.6576
Epoch 4/200
514/514 [==============================] - 0s 398us/step - loss: 0.5250 - acc: 0.7393
Epoch 5/200
514/514 [==============================] - 0s 295us/step - loss: 0.4965 - acc: 0.7724
Epoch 6/200
514/514 [==============================] - 0s 340us/step - loss: 0.4784 - acc: 0.7763
Epoch 7/200
514/514 [==============================] - 0s 325us/step - loss: 0.4676 - acc: 0.7763
Epoch 8/200
514/514 [==============================] - 0s 521us/step - loss: 0.4586 - acc: 0.7860
Epoch 9/200
514/514 [==============================] - 0s 424us/step - loss: 0.4534 - acc: 0.7899
Epoch 10/200
514/514 [==============================] - 0s 370us/step - loss: 0.4511 - acc

514/514 [==============================] - 0s 224us/step - loss: 0.3924 - acc: 0.8016
Epoch 84/200
514/514 [==============================] - 0s 219us/step - loss: 0.3925 - acc: 0.7996
Epoch 85/200
514/514 [==============================] - 0s 259us/step - loss: 0.3897 - acc: 0.7977
Epoch 86/200
514/514 [==============================] - 0s 596us/step - loss: 0.3906 - acc: 0.8016
Epoch 87/200
514/514 [==============================] - 0s 346us/step - loss: 0.3888 - acc: 0.7957
Epoch 88/200
514/514 [==============================] - 0s 297us/step - loss: 0.3887 - acc: 0.7996
Epoch 89/200
514/514 [==============================] - 0s 245us/step - loss: 0.3886 - acc: 0.8016
Epoch 90/200
514/514 [==============================] - 0s 289us/step - loss: 0.3880 - acc: 0.8016
Epoch 91/200
514/514 [==============================] - 0s 377us/step - loss: 0.3878 - acc: 0.8016
Epoch 92/200
514/514 [==============================] - 0s 420us/step - loss: 0.3870 - acc: 0.8016
Epoch 93/200
514/514 [=

514/514 [==============================] - 0s 250us/step - loss: 0.3664 - acc: 0.8230
Epoch 166/200
514/514 [==============================] - 0s 285us/step - loss: 0.3664 - acc: 0.8210
Epoch 167/200
514/514 [==============================] - 0s 223us/step - loss: 0.3666 - acc: 0.8230
Epoch 168/200
514/514 [==============================] - 0s 367us/step - loss: 0.3647 - acc: 0.8268
Epoch 169/200
514/514 [==============================] - 0s 422us/step - loss: 0.3653 - acc: 0.8268
Epoch 170/200
514/514 [==============================] - 0s 240us/step - loss: 0.3663 - acc: 0.8191
Epoch 171/200
514/514 [==============================] - 0s 238us/step - loss: 0.3630 - acc: 0.8327
Epoch 172/200
514/514 [==============================] - 0s 363us/step - loss: 0.3664 - acc: 0.8210
Epoch 173/200
514/514 [==============================] - 0s 388us/step - loss: 0.3646 - acc: 0.8249
Epoch 174/200
514/514 [==============================] - 0s 295us/step - loss: 0.3631 - acc: 0.8230
Epoch 175/200


In [20]:
# Avalia o modelo com os dados de teste
# Uma vez treinado o modelo, podemos avaliá-lo no conjunto de testes que contém novos exemplos não vistos. 
# Desta forma, podemos obter o valor mínimo alcançado pela função objetivo e o melhor valor alcançado pela métrica 
# de avaliação. Note-se que o conjunto de treinamento e o conjunto de teste são rigorosamente separados. 
# Não vale a pena avaliar um modelo em um exemplo que já foi usado para treinamento. 
# A aprendizagem é essencialmente um processo destinado a generalizar observações invisíveis e não a memorizar 
# o que já é conhecido.
loss, accuracy = model.evaluate(X_test, y_test)
print("\nLoss: %.2f, Acurácia: %.2f%%" % (loss, accuracy*100))

254/254 [==============================] - 0s 281us/step

Loss: 0.61, Acurácia: 78.74%


In [21]:
# Gera as previsões

mu, sigma = X.mean(axis=0), X.std(axis=0)
X = (X - mu) / sigma
predictions = model.predict(X)

In [22]:
predictions[:3]

array([[0.4446],
       [0.0361],
       [0.9137]], dtype=float32)

In [23]:
# Ajusta as previsões e imprime o resultado
rounded = [round(x[0]) for x in predictions]
print(rounded)
accuracy = numpy.mean(rounded == Y)
print("Acurácia das Previsões: %.2f%%" % (accuracy*100))

[0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0,