<a href="https://colab.research.google.com/github/vladimiralencar/DeepLearning_LANA/blob/master/keras/keras_MNIST_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Construindo uma Rede Neural - MNIST

http://yann.lecun.com/exdb/mnist/

In [0]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from time import time

In [0]:
np.random.seed(1337)

In [0]:
# /media/datasets/DeepLearningI/Cap02/mnist.csv
df = pd.read_csv('mnist.csv')

In [0]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [0]:
print(list(df.pixel40.value_counts()))

[41937, 3, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [0]:
df_train = df.iloc[:33600, :]

X_train = df_train.iloc[:, 1:].values / 255.
y_train = df_train['label'].values
y_train_onehot = pd.get_dummies(df_train['label']).values

In [0]:
df_test = df.iloc[33600:, :]

X_test = df_test.iloc[:, 1:].values / 255.
y_test = df_test['label'].values

In [0]:
X_test[:1]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [0]:
y_test[:10]

array([0, 7, 7, 2, 2, 6, 5, 7, 8, 5])

In [0]:
y_train_onehot[:2]

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

## Criando um Modelo de Árvore de Decisão ( Benchmark)

In [0]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=0, verbose=3)
model = model.fit(X_train, df_train['label'].values)

y_prediction = model.predict(X_test)
print ("\nAcurácia", np.sum(y_prediction == df_test['label'].values) / float(len(y_test)))

building tree 1 of 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s


building tree 2 of 10


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s


building tree 3 of 10
building tree 4 of 10
building tree 5 of 10
building tree 6 of 10
building tree 7 of 10
building tree 8 of 10
building tree 9 of 10
building tree 10 of 10

Acurácia 0.9378571428571428


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.5s finished
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s finished


## RNA com 1 Camada

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation

start = time()

model = Sequential()

model.add(Dense(input_dim=784, units=10))

model.add(Activation("softmax"))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train_onehot)

print ('\nTempo gasto: %s segundos' % str(time() - start))

Epoch 1/1
33600/33600 [==============================] - 4s 121us/step - loss: 0.9550 - acc: 0.7825

Tempo gasto: 4.4676430225372314 segundos


In [0]:
y_prediction = model.predict_classes(X_test)
print ("\n\nAcurácia", np.sum(y_prediction == y_test) / float(len(y_test)))



Acurácia 0.8598809523809524


## RNA com 2 Camadas

In [0]:
start = time()

model = Sequential()

model.add(Dense(input_dim=784, units=100))

model.add(Dense(units=10))

model.add(Activation("softmax"))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train_onehot)

print ('\nTempo gasto: %s segundos' % str(time() - start))

Epoch 1/1
33600/33600 [==============================] - 5s 158us/step - loss: 0.7070 - acc: 0.8183

Tempo gasto: 5.784822225570679 segundos


In [0]:
y_prediction = model.predict_classes(X_test)
print ("\n\nAcurácia", np.sum(y_prediction == y_test) / float(len(y_test)))



Acurácia 0.8864285714285715


## RNA com 3 Camadas

In [0]:
start = time()

model = Sequential()

model.add(Dense(input_dim=784, units=100))

model.add(Dense(units=100))

model.add(Dense(units=10))

model.add(Activation("softmax"))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train_onehot)

print ('\nTempo gasto: %s segundos' % str(time() - start))

Epoch 1/1
33600/33600 [==============================] - 5s 141us/step - loss: 0.6150 - acc: 0.8357

Tempo gasto: 5.110149145126343 segundos


In [0]:
y_prediction = model.predict_classes(X_test)
print ("\n\nAcurácia", np.sum(y_prediction == y_test) / float(len(y_test)))



Acurácia 0.8961904761904762


## RNA com 4 Camadas

In [0]:
start = time()

model = Sequential()

model.add(Dense(input_dim=784, units=100))

model.add(Dense(units=200))

model.add(Dense(units=200))

model.add(Dense(units=10))

model.add(Activation("softmax"))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train_onehot, epochs=30)

print ('\nTempo gasto: %s segundos' % str(time() - start))

Epoch 1/30
33600/33600 [==============================] - 6s 174us/step - loss: 0.5663 - acc: 0.8449
Epoch 2/30
33600/33600 [==============================] - ETA: 0s - loss: 0.3389 - acc: 0.901 - 5s 145us/step - loss: 0.3383 - acc: 0.9017
Epoch 3/30
33600/33600 [==============================] - 5s 135us/step - loss: 0.3114 - acc: 0.9113
Epoch 4/30
33600/33600 [==============================] - 5s 136us/step - loss: 0.2972 - acc: 0.9146
Epoch 5/30
33600/33600 [==============================] - 5s 142us/step - loss: 0.2889 - acc: 0.9185
Epoch 6/30
33600/33600 [==============================] - 4s 129us/step - loss: 0.2819 - acc: 0.9191
Epoch 7/30
33600/33600 [==============================] - 5s 149us/step - loss: 0.2763 - acc: 0.9207
Epoch 8/30
33600/33600 [==============================] - 7s 198us/step - loss: 0.2724 - acc: 0.9229
Epoch 9/30
33600/33600 [==============================] - 5s 135us/step - loss: 0.2688 - acc: 0.9233
Epoch 10/30
33600/33600 [============================

In [0]:
y_prediction = model.predict_classes(X_test)
print ("\n\nAcurácia", np.sum(y_prediction == y_test) / float(len(y_test)))



Acurácia 0.9198809523809524


# Fim