<a href="https://colab.research.google.com/github/vladimiralencar/DeepLearning_LANA/blob/master/keras/keras_MNIST_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Construindo uma Rede Neural - MNIST

http://yann.lecun.com/exdb/mnist/

In [0]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from time import time

In [0]:
np.random.seed(1337)

## Carregando os dados

In [5]:
from google.colab import files
uploaded = files.upload()

Saving mnist.csv.zip to mnist.csv.zip


In [8]:
!unzip mnist.csv.zip

Archive:  mnist.csv.zip
  inflating: mnist.csv               
   creating: __MACOSX/
  inflating: __MACOSX/._mnist.csv    


In [9]:
!ls

__MACOSX  mnist.csv  mnist.csv.zip  sample_data


In [0]:
# /media/datasets/DeepLearningI/Cap02/mnist.csv
df = pd.read_csv('mnist.csv')

In [11]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [12]:
len(df)

42000

In [13]:
print(list(df.pixel40.value_counts()))

[41937, 3, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [0]:
df_train = df.iloc[:33600, :]

X_train = df_train.iloc[:, 1:].values / 255.
y_train = df_train['label'].values
y_train_onehot = pd.get_dummies(df_train['label']).values

In [0]:
df_test = df.iloc[33600:, :]

X_test = df_test.iloc[:, 1:].values / 255.
y_test = df_test['label'].values

In [17]:
X_test[:1]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [18]:
y_test[:10]

array([0, 7, 7, 2, 2, 6, 5, 7, 8, 5])

In [19]:
y_train_onehot[:2]

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

## Criando um Modelo de Árvore de Decisão ( Benchmark)

In [20]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=0, verbose=3)
model = model.fit(X_train, df_train['label'].values)

y_prediction = model.predict(X_test)
print ("\nAcurácia", np.sum(y_prediction == df_test['label'].values) / float(len(y_test)))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


building tree 1 of 10


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s


building tree 2 of 10


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.6s remaining:    0.0s


building tree 3 of 10
building tree 4 of 10
building tree 5 of 10
building tree 6 of 10
building tree 7 of 10
building tree 8 of 10
building tree 9 of 10
building tree 10 of 10

Acurácia 0.9379761904761905


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.9s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s finished


## RNA com 1 Camada

In [23]:
from keras.models import Sequential
from keras.layers import Dense, Activation

start = time()

model = Sequential()

model.add(Dense(input_dim=784, units=10))

model.add(Activation("softmax"))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train_onehot, epochs=10)  # 10 passadas por todo conjunto de dados

print ('\nTempo gasto: %s segundos' % str(time() - start))

Epoch 1/10
33600/33600 [==============================] - 3s 75us/step - loss: 0.9445 - acc: 0.7838
Epoch 2/10
33600/33600 [==============================] - 2s 60us/step - loss: 0.5309 - acc: 0.8665
Epoch 3/10
33600/33600 [==============================] - 2s 60us/step - loss: 0.4559 - acc: 0.8811
Epoch 4/10
33600/33600 [==============================] - 2s 59us/step - loss: 0.4189 - acc: 0.8886
Epoch 5/10
33600/33600 [==============================] - 2s 60us/step - loss: 0.3955 - acc: 0.8930
Epoch 6/10
33600/33600 [==============================] - 2s 60us/step - loss: 0.3794 - acc: 0.8963
Epoch 7/10
33600/33600 [==============================] - 2s 60us/step - loss: 0.3672 - acc: 0.8996
Epoch 8/10
33600/33600 [==============================] - 2s 60us/step - loss: 0.3574 - acc: 0.9016
Epoch 9/10
33600/33600 [==============================] - 2s 60us/step - loss: 0.3495 - acc: 0.9039
Epoch 10/10
33600/33600 [==============================] - 2s 60us/step - loss: 0.3427 - acc: 0.9053

In [24]:
y_prediction = model.predict_classes(X_test)
print ("\n\nAcurácia", np.sum(y_prediction == y_test) / float(len(y_test)))



Acurácia 0.9076190476190477


## RNA com 2 Camadas

In [25]:
start = time()

model = Sequential()

model.add(Dense(input_dim=784, units=100))

model.add(Dense(units=10))

model.add(Activation("softmax"))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train_onehot, epochs=10)

print ('\nTempo gasto: %s segundos' % str(time() - start))

Epoch 1/10
33600/33600 [==============================] - 3s 103us/step - loss: 0.7145 - acc: 0.8166
Epoch 2/10
33600/33600 [==============================] - 3s 85us/step - loss: 0.3967 - acc: 0.8901
Epoch 3/10
33600/33600 [==============================] - 3s 84us/step - loss: 0.3515 - acc: 0.9001
Epoch 4/10
33600/33600 [==============================] - 3s 86us/step - loss: 0.3296 - acc: 0.9066
Epoch 5/10
33600/33600 [==============================] - 3s 87us/step - loss: 0.3157 - acc: 0.9110
Epoch 6/10
33600/33600 [==============================] - 3s 85us/step - loss: 0.3064 - acc: 0.9136
Epoch 7/10
33600/33600 [==============================] - 3s 85us/step - loss: 0.2992 - acc: 0.9154
Epoch 8/10
33600/33600 [==============================] - 3s 85us/step - loss: 0.2933 - acc: 0.9174
Epoch 9/10
33600/33600 [==============================] - 3s 87us/step - loss: 0.2886 - acc: 0.9187
Epoch 10/10
33600/33600 [==============================] - 3s 86us/step - loss: 0.2848 - acc: 0.919

In [26]:
y_prediction = model.predict_classes(X_test)
print ("\n\nAcurácia", np.sum(y_prediction == y_test) / float(len(y_test)))



Acurácia 0.919047619047619


## RNA com 3 Camadas

In [27]:
start = time()

model = Sequential()

model.add(Dense(input_dim=784, units=100))

model.add(Dense(units=100))

model.add(Dense(units=10))

model.add(Activation("softmax"))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train_onehot, epochs=10)

print ('\nTempo gasto: %s segundos' % str(time() - start))

Epoch 1/10
33600/33600 [==============================] - 3s 104us/step - loss: 0.6262 - acc: 0.8295
Epoch 2/10
33600/33600 [==============================] - 3s 90us/step - loss: 0.3535 - acc: 0.8982
Epoch 3/10
33600/33600 [==============================] - 3s 91us/step - loss: 0.3214 - acc: 0.9074
Epoch 4/10
33600/33600 [==============================] - 3s 91us/step - loss: 0.3047 - acc: 0.9125
Epoch 5/10
33600/33600 [==============================] - 3s 90us/step - loss: 0.2951 - acc: 0.9151
Epoch 6/10
33600/33600 [==============================] - 3s 90us/step - loss: 0.2879 - acc: 0.9174
Epoch 7/10
33600/33600 [==============================] - 3s 92us/step - loss: 0.2819 - acc: 0.9193
Epoch 8/10
33600/33600 [==============================] - 3s 92us/step - loss: 0.2779 - acc: 0.9203
Epoch 9/10
33600/33600 [==============================] - 3s 91us/step - loss: 0.2733 - acc: 0.9230
Epoch 10/10
33600/33600 [==============================] - 3s 91us/step - loss: 0.2702 - acc: 0.922

In [28]:
y_prediction = model.predict_classes(X_test)
print ("\n\nAcurácia", np.sum(y_prediction == y_test) / float(len(y_test)))



Acurácia 0.9207142857142857


## RNA com 4 Camadas

In [29]:
start = time()

model = Sequential()

model.add(Dense(input_dim=784, units=100))

model.add(Dense(units=200))

model.add(Dense(units=200))

model.add(Dense(units=10))

model.add(Activation("softmax"))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

model.fit(X_train, y_train_onehot, epochs=30)

print ('\nTempo gasto: %s segundos' % str(time() - start))

Epoch 1/30
33600/33600 [==============================] - 4s 111us/step - loss: 0.5630 - acc: 0.8439
Epoch 2/30
33600/33600 [==============================] - 4s 107us/step - loss: 0.3406 - acc: 0.9021
Epoch 3/30
33600/33600 [==============================] - 3s 102us/step - loss: 0.3132 - acc: 0.9108
Epoch 4/30
33600/33600 [==============================] - 3s 103us/step - loss: 0.2988 - acc: 0.9139
Epoch 5/30
33600/33600 [==============================] - 3s 102us/step - loss: 0.2905 - acc: 0.9173
Epoch 6/30
33600/33600 [==============================] - 3s 102us/step - loss: 0.2834 - acc: 0.9188
Epoch 7/30
33600/33600 [==============================] - 3s 102us/step - loss: 0.2778 - acc: 0.9211
Epoch 8/30
33600/33600 [==============================] - 3s 102us/step - loss: 0.2730 - acc: 0.9218
Epoch 9/30
33600/33600 [==============================] - 3s 103us/step - loss: 0.2699 - acc: 0.9230
Epoch 10/30
33600/33600 [==============================] - 3s 103us/step - loss: 0.2666 - a

In [30]:
y_prediction = model.predict_classes(X_test)
print ("\n\nAcurácia", np.sum(y_prediction == y_test) / float(len(y_test)))



Acurácia 0.9214285714285714
